openapi: 3.0.0
info:
  title: RocketCart Storefront API
  version: 1.0.0
servers:
  - url: https://e14290-mr.myshopify.com
paths:
  /api/2023-07/graphql.json:
    post:
      operationId: storefrontGraphQL
      summary: Send GraphQL query to Shopify Storefront API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: Response from Storefront API
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    shopifyAccessToken:
      type: apiKey
      in: header
      name: X-Shopify-Storefront-Access-Token
security:
  - shopifyAccessToken: []
