openapi: 3.1.0
info:
  title: Shopify Storefront GraphQL API
  version: 2023-07
servers:
  - url: https://e14290-mr.myshopify.com/api/2023-07
paths:
  /graphql.json:
    post:
      operationId: storefrontGraphQL
      summary: Send a GraphQL query to the Shopify Storefront API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                variables:
                  type: object
      responses:
        '200':
          description: Successful GraphQL response
          content:
            application/json:
              schema:
                type: object
      security:
        - shopifyStorefrontToken: []
components:
  securitySchemes:
    shopifyStorefrontToken:
      type: apiKey
      in: header
      name: X-Shopify-Storefront-Access-Token
