openapi: 3.1.0
info:
  title: RocketCart Storefront API Proxy
  version: 1.0.0
servers:
  - url: https://rocketcart9-c34v.vercel.app
paths:
  /api/storefront-graphql:
    post:
      operationId: storefrontGraphQL
      summary: Send a GraphQL query to Shopify Storefront API via RocketCart proxy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                variables:
                  type: object
      responses:
        '200':
          description: Shopify Storefront GraphQL response
          content:
            application/json:
              schema:
                type: object
