openapi: 3.1.0
info:
  title: RocketCart Storefront API
  version: 1.0.0
servers:
  - url: https://e14290-mr.myshopify.com/admin/api/2025-07/graphql.json
paths:
  /storefront-graphql:
    post:
      operationId: storefrontGraphQL
      summary: Send GraphQL query to Shopify Storefront API (wrapped in REST)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
      responses:
        '200':
          description: GraphQL response
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    shopifyAccessToken:
      type: apiKey
      in: header
      name: X-Shopify-Storefront-Access-Token
security:
  - shopifyAccessToken: []
