openapi: 3.1.0
info:
  title: Shopify Admin GraphQL API
  version: 2025-07
servers:
  - url: https://e14290-mr.myshopify.com/admin/api/2025-07
paths:
  /graphql.json:
    post:
      operationId: postAdminGraphQL
      summary: Send a GraphQL query to the Shopify Admin API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                variables:
                  type: object
      responses:
        '200':
          description: GraphQL response
          content:
            application/json:
              schema:
                type: object
      security:
        - shopifyAdminToken: []
components:
  securitySchemes:
    shopifyAdminToken:
      type: apiKey
      in: header
      name: X-Shopify-Access-Token
