openapi: 3.0.0
info:
  title: RocketCart Storefront API
  version: 1.0.0
servers:
  - url: https://e14290-mr.myshopify.com/api/2024-07
paths:
  /graphql.json:
    post:
      summary: Shopify Storefront GraphQL
      operationId: storefrontGraphQL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: A complete GraphQL query string
      responses:
        "200":
          description: Successful GraphQL response
          content:
            application/json:
              schema:
                type: object
